### ISSUE TITLE
Plugin setup failing to install cryptography

### ISSUE THREAD

**Issue by AllenMcAfee** [Robo3D/OctoPrint-PolarCloud#1]
Testing on RoboOS 2.0.

Initial installation of plugin via Plugin Manager fails with response: `Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-OlOBtm/cryptography`

after investigating, it appears to be an issue with cffi 0.8.6.1 no being compatible.  the following steps corrects the issue and allows for installation:

- Activate environment `source ~/oprint/bin/activate`
- Apply update due to some archives not being fetched: `sudo apt-get update`
- Install dependencies: `sudo apt-get install build-essential libssl-dev libffi-dev python-dev`
- Install cffi 1.11.4: `pip install cffi`
- Install cryptography: `pip install cryptography`

The last two steps are applied during plugin installation, so are probably not needed.  

After these steps are applied, the plugin should install successfully.

**Comment by Ximidar** [comment]
I made another branch with a hopeful fix. Please try to install it.  https://github.com/Robo3D/OctoPrint-PolarCloud/archive/1.3.Robo.zip

**Comment by Ximidar** [comment]
This install will take a very long time

**Comment by Ximidar** [comment]
So far this install has worked on an R2 and a C2.

**Comment by AllenMcAfee** [comment]
@Ximidar which branch contains this fix?  I cannot seem to find it here.

**Comment by AllenMcAfee** [comment]
@Ximidar nm, i found it under Automatically_install_dependencies

**Comment by Ximidar** [comment]
@AllenMcAfee You mentioned that the install fails in passing, is that still true?

**Comment by AllenMcAfee** [comment]
Fixed with latest updates to dependencies.
